### ISSUE TITLE
The appimage does not work on Fedora.

### ISSUE THREAD

**Issue by GADT-SV** [death7654/Chrultrabook-Tools#92]
Hello, running the AppImage or installing the RPM file always yields the same result, "EC Tool Binary not found." Even running as root. The real question is - where is your program looking for the EC Tool binary files?

When running the ectool binaries from here (https://files.tree123.org/utils/x86_64/gnu/ectool), I have full control over the fans, but the question is where can I drop this file so your program reads it and runs with it?

Thank you brother!

**Comment by death7654** [comment]
Hi, please download the appimage, if you would like to use the RPM file you would have to drop the files, marked as executeable, in /usr/bin but thats not reccomended. The binaries should be prebundled with the appimage. 

Thank you

**Comment by GADT-SV** [comment]
![Image](https://github.com/user-attachments/assets/0c1c27ac-a945-48f2-81f6-9eb127b8ccd5)

Moved to /usr/bin, ensured it's executable.. Not working with RPM, or appimage

**Comment by death7654** [comment]
can you show me the output of ectool hello?

**Comment by GADT-SV** [comment]
![Image](https://github.com/user-attachments/assets/d652d734-73e9-4b5f-9bd3-56a45620a960)

**Comment by death7654** [comment]
Start the app with sudo and see if it works

**Comment by GADT-SV** [comment]
![Image](https://github.com/user-attachments/assets/a059512b-68b8-473d-a93c-a918084bd67c)

**Comment by GADT-SV** [comment]
Using the latest version (oops, used 3.0.1 in last post):

![Image](https://github.com/user-attachments/assets/e1aaf00c-fa28-4724-92f8-0d0ecce88d58)

**Comment by GADT-SV** [comment]
Just installed webkit2gtk4.1, and still getting the same error

![Image](https://github.com/user-attachments/assets/0c96705f-561b-4d53-8272-b0fe03b6b0c2)

**Comment by death7654** [comment]
Contact me on the chrultrabook discord, and lets figure this out

**Comment by death7654** [comment]
This should work with the latest [3.0.3](https://github.com/death7654/Chrultrabook-Tools/releases/tag/3.0.3) release. Test it out :)

**Comment by death7654** [comment]
User has confirmed the problem has been solved. Closing Issue

**Comment by bam80** [comment]
Sorry, it's still an issue for me with [3.1.4](https://github.com/death7654/Chrultrabook-Tools/releases/tag/3.1.4).
Regression?
